- hosts: webservers
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update html page
      ansible.builtin.copy:
        src: files/test.html
        dest: /usr/share/nginx/html/index.html
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: files/prod.config
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes