- hosts: webservers
  vars:
    nginx_port: 8081
    root_dir: /var/tmp/www
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update html page
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{ root_dir }}/"
        directory_mode:
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: files/prod.config
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes